name: Build test

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup
      uses: './.github/actions/ci-setup'
      id: setup
      with:
        python-version: '3.x'

    - name: Build
      run: poetry build