name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup
      uses: './.github/actions/ci-setup'
      id: setup
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run unit tests
      run: poetry run pytest